seed_everything: 123
trainer:
  max_epochs: 5
  callbacks+:
    - class_path: ModelCheckpoint
      init_args:
        save_top_k: -1
        every_n_epochs: 1
model:
  class_path: src.models.SchemaEncoder
  init_args:
    model_name_or_path: all-mpnet-base-v2
    max_length: 256
    weight_decay: 0.0
    learning_rate: 2.0e-05
    scheduler_type: linear
    warmup_steps: 0
