seed_everything: 123
trainer:
  max_epochs: 20
model:
  class_path: src.models.SchemaRouting
  init_args:
    model_name_or_path: ./models/t5-base
    max_length: 256
    generator_config:
      max_new_tokens: 64
    weight_decay: 0.0
    learning_rate: 5.0e-05
    scheduler_type: linear
    warmup_steps: 0
