seed_everything: 123
trainer:
  max_epochs: 50
  # precision: "16-true"
  callbacks+:
    - class_path: ModelCheckpoint
      init_args:
        save_top_k: -1
        every_n_epochs: 5
model:
  class_path: src.models.SchemaQuestioning
  init_args:
    model_name_or_path: ./models/t5-base
    generator_config:
      max_new_tokens: 256
    max_length: 256
    weight_decay: 0.0
    learning_rate: 2.0e-05
    scheduler_type: linear
    warmup_steps: 0
data:
  class_path: src.datamodules.Schema2Text
  init_args:
    dataset: ""
    batch_size: 32
    num_workers: 8
