seed_everything: 123
trainer:
  max_epochs: 10
model:
  class_path: src.models.Seq2SeqModel
  init_args:
    model_name_or_path: ./models/t5-base
    weight_decay: 0.0
    learning_rate: 5.0e-05
    scheduler_type: linear
    warmup_steps: 0
