fit:
  debug: false
  gpus_per_trial: 1
  configs:
    - configs/schema_routing.yaml
  data_configs:
    - configs/data/spider.yaml
    - configs/data/bird.yaml
    - configs/data/fiben.yaml
  override_kwargs:
    seed_everything:
      - 123
    data.train_data:
      - synthetic
      # - original
      # - all
