fit:
  debug: false
  gpus_per_trial: 1
  configs:
    - configs/schema_routing.yaml
  data_configs:
    - configs/spider.yaml
    - configs/bird.yaml
    - configs/fiben.yaml
  override_kwargs:
    seed_everything:
      - 123
      # - 42
    model.learning_rate:
      - 2.0e-05
