fit:
  debug: false
  gpus_per_trial: 1
  configs:
    - configs/schema_contrastive.yaml
  data_configs:
    - configs/data/spider.yaml
    - configs/data/bird.yaml
    - configs/data/fiben.yaml
  override_kwargs:
    seed_everything:
      - 123
