fit:
  debug: false
  gpus_per_trial: 1
  configs:
    - configs/schema_questioning.yaml
  # data_configs:
  #   - configs/data/spider.yaml
  #   - configs/data/bird.yaml
  #   - configs/data/wikisql.yaml
  override_kwargs:
    seed_everything:
      - 123
    model.model_name_or_path:
      - "./models/t5-base"
      - "./models/all-t5-base-v1"
      - "./models/flan-t5-base"
