debug: false
gpus_per_trial: 1
configs:
  - configs/schema_routing.yaml
data_configs:
  - configs/spider.yaml
override_kwargs:
  seed_everything:
    - 123
    - 42
  model.delimiters:
    - initiator: "("
      separator: " "
      terminator: ")"
    - initiator: "("
      separator: "|"
      terminator: ")"
    - initiator: "<(>"
      separator: "< >"
      terminator: "<)>"
    - initiator: "<(>"
      separator: "<|>"
      terminator: "<)>"
    - initiator: "<extra_id_0>"
      separator: "<extra_id_1>"
      terminator: "<extra_id_2>"
