test:
  debug: false
  gpus_per_trial: 1
  ckpt_paths:
    - ""
  override_kwargs:
    model.generator_config:
      - constraint_decoding: true
        max_new_tokens: 30
        num_beams: 10
        num_beam_groups: 10
        diversity_penalty: 5.0
        length_penalty: 2.0
        num_return_sequences: 10
    data.batch_size:
      - 64
